CREATE TABLE Registrations
( Login1 CHAR(10) PRIMARY KEY NOT NULL,
  Password1 CHAR(255) NOT NULL,
  Email1 CHAR(30) UNIQUE NOT NULL,
  Date1 CHAR(20) NOT NULL
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE Enters
( Login1 CHAR(10) NOT NULL,
  Date2 CHAR(20) NOT NULL,
  Rate2 TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (Login1, Date2),
  FOREIGN KEY (Login1) REFERENCES Registrations(Login1)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
